fail_fast: true

repos:
  - repo: https://github.com/psf/black
    rev: 26.3.1
    hooks:
      - id: black
        language_version: python3.12
        args: [--check]
  - repo: local
    hooks:
      - id: pytest
        name: Run pytest
        entry: pytest
        language: python
        types: [python]
        pass_filenames: false
